server:
  port: 9084
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashishiitk/config-server
          default-label: main
          clone-on-start: true
          refresh-rate: 2000
  
  

